trigger: none

pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- bash: |
    set -euo pipefail

    echo "Running on: $(git rev-parse HEAD)"

    branch=$(Build.SourceBranchName)
    echo "Branch reported by Azure: $branch"
    if [ "$branch" == "main" ]; then
        exit 0
    else
        echo "Bumping main"
        git checkout main
        git -c "user.name=ci" -c "user.email=ci@eample.com" commit --allow-empty -m "bump sha"
        git push origin main
        exit 1
    fi
